// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/amass/enum/enum_message.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumConfig_Mode int32

const (
	EnumConfig_DEFAULT EnumConfig_Mode = 0
	EnumConfig_PASSIVE EnumConfig_Mode = 1
	EnumConfig_ACTIVE  EnumConfig_Mode = 2
)

// Enum value maps for EnumConfig_Mode.
var (
	EnumConfig_Mode_name = map[int32]string{
		0: "DEFAULT",
		1: "PASSIVE",
		2: "ACTIVE",
	}
	EnumConfig_Mode_value = map[string]int32{
		"DEFAULT": 0,
		"PASSIVE": 1,
		"ACTIVE":  2,
	}
)

func (x EnumConfig_Mode) Enum() *EnumConfig_Mode {
	p := new(EnumConfig_Mode)
	*p = x
	return p
}

func (x EnumConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_amass_enum_enum_message_proto_enumTypes[0].Descriptor()
}

func (EnumConfig_Mode) Type() protoreflect.EnumType {
	return &file_protos_amass_enum_enum_message_proto_enumTypes[0]
}

func (x EnumConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumConfig_Mode.Descriptor instead.
func (EnumConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_message_proto_rawDescGZIP(), []int{0, 0}
}

type EnumConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode         *EnumConfig_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=enum.EnumConfig_Mode,oneof" json:"mode,omitempty"`
	Timeout      *uint32          `protobuf:"varint,2,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	DnsResolvers []string         `protobuf:"bytes,3,rep,name=dnsResolvers,proto3" json:"dnsResolvers,omitempty"`
}

func (x *EnumConfig) Reset() {
	*x = EnumConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumConfig) ProtoMessage() {}

func (x *EnumConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumConfig.ProtoReflect.Descriptor instead.
func (*EnumConfig) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_message_proto_rawDescGZIP(), []int{0}
}

func (x *EnumConfig) GetMode() EnumConfig_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return EnumConfig_DEFAULT
}

func (x *EnumConfig) GetTimeout() uint32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *EnumConfig) GetDnsResolvers() []string {
	if x != nil {
		return x.DnsResolvers
	}
	return nil
}

type EnumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain string      `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Config *EnumConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
}

func (x *EnumRequest) Reset() {
	*x = EnumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumRequest) ProtoMessage() {}

func (x *EnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumRequest.ProtoReflect.Descriptor instead.
func (*EnumRequest) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_message_proto_rawDescGZIP(), []int{1}
}

func (x *EnumRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnumRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EnumRequest) GetConfig() *EnumConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EnumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *EnumResponse) Reset() {
	*x = EnumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse) ProtoMessage() {}

func (x *EnumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse.ProtoReflect.Descriptor instead.
func (*EnumResponse) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_message_proto_rawDescGZIP(), []int{2}
}

func (x *EnumResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnumResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_protos_amass_enum_enum_message_proto protoreflect.FileDescriptor

var file_protos_amass_enum_enum_message_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0xc2, 0x01, 0x0a,
	0x0a, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x73, 0x22, 0x2c,
	0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c,
	0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x53, 0x53, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x22, 0x6f, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x36, 0x0a, 0x0c, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x66, 0x65, 0x65, 0x62, 0x72,
	0x69, 0x61, 0x6e, 0x2f, 0x63, 0x61, 0x70, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_amass_enum_enum_message_proto_rawDescOnce sync.Once
	file_protos_amass_enum_enum_message_proto_rawDescData = file_protos_amass_enum_enum_message_proto_rawDesc
)

func file_protos_amass_enum_enum_message_proto_rawDescGZIP() []byte {
	file_protos_amass_enum_enum_message_proto_rawDescOnce.Do(func() {
		file_protos_amass_enum_enum_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_amass_enum_enum_message_proto_rawDescData)
	})
	return file_protos_amass_enum_enum_message_proto_rawDescData
}

var file_protos_amass_enum_enum_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_amass_enum_enum_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_amass_enum_enum_message_proto_goTypes = []interface{}{
	(EnumConfig_Mode)(0), // 0: enum.EnumConfig.Mode
	(*EnumConfig)(nil),   // 1: enum.EnumConfig
	(*EnumRequest)(nil),  // 2: enum.EnumRequest
	(*EnumResponse)(nil), // 3: enum.EnumResponse
}
var file_protos_amass_enum_enum_message_proto_depIdxs = []int32{
	0, // 0: enum.EnumConfig.mode:type_name -> enum.EnumConfig.Mode
	1, // 1: enum.EnumRequest.config:type_name -> enum.EnumConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_amass_enum_enum_message_proto_init() }
func file_protos_amass_enum_enum_message_proto_init() {
	if File_protos_amass_enum_enum_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_amass_enum_enum_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_enum_enum_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_enum_enum_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_amass_enum_enum_message_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_protos_amass_enum_enum_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_amass_enum_enum_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_amass_enum_enum_message_proto_goTypes,
		DependencyIndexes: file_protos_amass_enum_enum_message_proto_depIdxs,
		EnumInfos:         file_protos_amass_enum_enum_message_proto_enumTypes,
		MessageInfos:      file_protos_amass_enum_enum_message_proto_msgTypes,
	}.Build()
	File_protos_amass_enum_enum_message_proto = out.File
	file_protos_amass_enum_enum_message_proto_rawDesc = nil
	file_protos_amass_enum_enum_message_proto_goTypes = nil
	file_protos_amass_enum_enum_message_proto_depIdxs = nil
}
