// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: protos/amass/enum/enum_service.proto

package enum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnumServiceClient is the client API for EnumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnumServiceClient interface {
	Run(ctx context.Context, in *EnumRequest, opts ...grpc.CallOption) (*EnumResponse, error)
}

type enumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnumServiceClient(cc grpc.ClientConnInterface) EnumServiceClient {
	return &enumServiceClient{cc}
}

func (c *enumServiceClient) Run(ctx context.Context, in *EnumRequest, opts ...grpc.CallOption) (*EnumResponse, error) {
	out := new(EnumResponse)
	err := c.cc.Invoke(ctx, "/enum.EnumService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnumServiceServer is the server API for EnumService service.
// All implementations must embed UnimplementedEnumServiceServer
// for forward compatibility
type EnumServiceServer interface {
	Run(context.Context, *EnumRequest) (*EnumResponse, error)
	mustEmbedUnimplementedEnumServiceServer()
}

// UnimplementedEnumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnumServiceServer struct {
}

func (UnimplementedEnumServiceServer) Run(context.Context, *EnumRequest) (*EnumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedEnumServiceServer) mustEmbedUnimplementedEnumServiceServer() {}

// UnsafeEnumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnumServiceServer will
// result in compilation errors.
type UnsafeEnumServiceServer interface {
	mustEmbedUnimplementedEnumServiceServer()
}

func RegisterEnumServiceServer(s grpc.ServiceRegistrar, srv EnumServiceServer) {
	s.RegisterService(&EnumService_ServiceDesc, srv)
}

func _EnumService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/enum.EnumService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServiceServer).Run(ctx, req.(*EnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnumService_ServiceDesc is the grpc.ServiceDesc for EnumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enum.EnumService",
	HandlerType: (*EnumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _EnumService_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/amass/enum/enum_service.proto",
}
