// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protos/amass/enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domains []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *EnumRequest) Reset() {
	*x = EnumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumRequest) ProtoMessage() {}

func (x *EnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumRequest.ProtoReflect.Descriptor instead.
func (*EnumRequest) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_proto_rawDescGZIP(), []int{0}
}

func (x *EnumRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type EnumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EnumResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *EnumResponse) Reset() {
	*x = EnumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse) ProtoMessage() {}

func (x *EnumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse.ProtoReflect.Descriptor instead.
func (*EnumResponse) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_proto_rawDescGZIP(), []int{1}
}

func (x *EnumResponse) GetResults() []*EnumResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type EnumResponse_Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Cidr string `protobuf:"bytes,2,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
	ASN  uint32 `protobuf:"varint,3,opt,name=ASN,proto3" json:"ASN,omitempty"`
	Desc string `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *EnumResponse_Address) Reset() {
	*x = EnumResponse_Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumResponse_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse_Address) ProtoMessage() {}

func (x *EnumResponse_Address) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse_Address.ProtoReflect.Descriptor instead.
func (*EnumResponse_Address) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EnumResponse_Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EnumResponse_Address) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *EnumResponse_Address) GetASN() uint32 {
	if x != nil {
		return x.ASN
	}
	return 0
}

func (x *EnumResponse_Address) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type EnumResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain    string                  `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Addresses []*EnumResponse_Address `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Tag       string                  `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *EnumResponse_Result) Reset() {
	*x = EnumResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_enum_enum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumResponse_Result) ProtoMessage() {}

func (x *EnumResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_enum_enum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumResponse_Result.ProtoReflect.Descriptor instead.
func (*EnumResponse_Result) Descriptor() ([]byte, []int) {
	return file_protos_amass_enum_enum_proto_rawDescGZIP(), []int{1, 1}
}

func (x *EnumResponse_Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumResponse_Result) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EnumResponse_Result) GetAddresses() []*EnumResponse_Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *EnumResponse_Result) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_protos_amass_enum_enum_proto protoreflect.FileDescriptor

var file_protos_amass_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x65, 0x6e, 0x75, 0x6d, 0x22, 0x27, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x9b, 0x02,
	0x0a, 0x0c, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x1a, 0x53, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69,
	0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x53, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x41, 0x53, 0x4e, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x1a, 0x80, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x38, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x32, 0x48, 0x0a, 0x0b, 0x45,
	0x6e, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x65,
	0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x66, 0x65, 0x65, 0x62, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x63,
	0x61, 0x70, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61,
	0x6d, 0x61, 0x73, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_amass_enum_enum_proto_rawDescOnce sync.Once
	file_protos_amass_enum_enum_proto_rawDescData = file_protos_amass_enum_enum_proto_rawDesc
)

func file_protos_amass_enum_enum_proto_rawDescGZIP() []byte {
	file_protos_amass_enum_enum_proto_rawDescOnce.Do(func() {
		file_protos_amass_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_amass_enum_enum_proto_rawDescData)
	})
	return file_protos_amass_enum_enum_proto_rawDescData
}

var file_protos_amass_enum_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_amass_enum_enum_proto_goTypes = []interface{}{
	(*EnumRequest)(nil),          // 0: enum.EnumRequest
	(*EnumResponse)(nil),         // 1: enum.EnumResponse
	(*EnumResponse_Address)(nil), // 2: enum.EnumResponse.Address
	(*EnumResponse_Result)(nil),  // 3: enum.EnumResponse.Result
}
var file_protos_amass_enum_enum_proto_depIdxs = []int32{
	3, // 0: enum.EnumResponse.results:type_name -> enum.EnumResponse.Result
	2, // 1: enum.EnumResponse.Result.addresses:type_name -> enum.EnumResponse.Address
	0, // 2: enum.EnumService.BasicEnumerate:input_type -> enum.EnumRequest
	1, // 3: enum.EnumService.BasicEnumerate:output_type -> enum.EnumResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_amass_enum_enum_proto_init() }
func file_protos_amass_enum_enum_proto_init() {
	if File_protos_amass_enum_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_amass_enum_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_enum_enum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_enum_enum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumResponse_Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_enum_enum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_amass_enum_enum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_amass_enum_enum_proto_goTypes,
		DependencyIndexes: file_protos_amass_enum_enum_proto_depIdxs,
		MessageInfos:      file_protos_amass_enum_enum_proto_msgTypes,
	}.Build()
	File_protos_amass_enum_enum_proto = out.File
	file_protos_amass_enum_enum_proto_rawDesc = nil
	file_protos_amass_enum_enum_proto_goTypes = nil
	file_protos_amass_enum_enum_proto_depIdxs = nil
}
