// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: protos/amass/db/db_message.proto

package db

import (
	amass "github.com/kofeebrian/capamass/protos/amass"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of protos/amass/result.proto.

type Address = amass.Address
type EnumResult = amass.EnumResult
type Domains = amass.Domains
type Event = amass.Event

type DBConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latest bool `protobuf:"varint,1,opt,name=latest,proto3" json:"latest,omitempty"`
}

func (x *DBConfig) Reset() {
	*x = DBConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_db_db_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBConfig) ProtoMessage() {}

func (x *DBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_db_db_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBConfig.ProtoReflect.Descriptor instead.
func (*DBConfig) Descriptor() ([]byte, []int) {
	return file_protos_amass_db_db_message_proto_rawDescGZIP(), []int{0}
}

func (x *DBConfig) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

type DBResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events  []*amass.Event   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Domains []*amass.Domains `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *DBResult) Reset() {
	*x = DBResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_db_db_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBResult) ProtoMessage() {}

func (x *DBResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_db_db_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBResult.ProtoReflect.Descriptor instead.
func (*DBResult) Descriptor() ([]byte, []int) {
	return file_protos_amass_db_db_message_proto_rawDescGZIP(), []int{1}
}

func (x *DBResult) GetEvents() []*amass.Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DBResult) GetDomains() []*amass.Domains {
	if x != nil {
		return x.Domains
	}
	return nil
}

type DBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain *string   `protobuf:"bytes,2,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	Config *DBConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
}

func (x *DBRequest) Reset() {
	*x = DBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_db_db_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRequest) ProtoMessage() {}

func (x *DBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_db_db_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRequest.ProtoReflect.Descriptor instead.
func (*DBRequest) Descriptor() ([]byte, []int) {
	return file_protos_amass_db_db_message_proto_rawDescGZIP(), []int{2}
}

func (x *DBRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBRequest) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *DBRequest) GetConfig() *DBConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain *string   `protobuf:"bytes,2,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	Result *DBResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DBResponse) Reset() {
	*x = DBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_amass_db_db_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBResponse) ProtoMessage() {}

func (x *DBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_amass_db_db_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBResponse.ProtoReflect.Descriptor instead.
func (*DBResponse) Descriptor() ([]byte, []int) {
	return file_protos_amass_db_db_message_proto_rawDescGZIP(), []int{3}
}

func (x *DBResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBResponse) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *DBResponse) GetResult() *DBResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_protos_amass_db_db_message_proto protoreflect.FileDescriptor

var file_protos_amass_db_db_message_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x64,
	0x62, 0x2f, 0x64, 0x62, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x64, 0x62, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61,
	0x6d, 0x61, 0x73, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x22, 0x0a, 0x08, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x08, 0x44, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1e, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x22, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x07, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x79, 0x0a, 0x09, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x29, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x64, 0x62, 0x2e, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x01, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x6a, 0x0a, 0x0a, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x62,
	0x2e, 0x44, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x66, 0x65, 0x65,
	0x62, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x63, 0x61, 0x70, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x73, 0x73, 0x2f, 0x64, 0x62, 0x50, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_amass_db_db_message_proto_rawDescOnce sync.Once
	file_protos_amass_db_db_message_proto_rawDescData = file_protos_amass_db_db_message_proto_rawDesc
)

func file_protos_amass_db_db_message_proto_rawDescGZIP() []byte {
	file_protos_amass_db_db_message_proto_rawDescOnce.Do(func() {
		file_protos_amass_db_db_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_amass_db_db_message_proto_rawDescData)
	})
	return file_protos_amass_db_db_message_proto_rawDescData
}

var file_protos_amass_db_db_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_amass_db_db_message_proto_goTypes = []interface{}{
	(*DBConfig)(nil),      // 0: db.DBConfig
	(*DBResult)(nil),      // 1: db.DBResult
	(*DBRequest)(nil),     // 2: db.DBRequest
	(*DBResponse)(nil),    // 3: db.DBResponse
	(*amass.Event)(nil),   // 4: Event
	(*amass.Domains)(nil), // 5: Domains
}
var file_protos_amass_db_db_message_proto_depIdxs = []int32{
	4, // 0: db.DBResult.events:type_name -> Event
	5, // 1: db.DBResult.domains:type_name -> Domains
	0, // 2: db.DBRequest.config:type_name -> db.DBConfig
	1, // 3: db.DBResponse.result:type_name -> db.DBResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_amass_db_db_message_proto_init() }
func file_protos_amass_db_db_message_proto_init() {
	if File_protos_amass_db_db_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_amass_db_db_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_db_db_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_db_db_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_amass_db_db_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_amass_db_db_message_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_protos_amass_db_db_message_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_amass_db_db_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_amass_db_db_message_proto_goTypes,
		DependencyIndexes: file_protos_amass_db_db_message_proto_depIdxs,
		MessageInfos:      file_protos_amass_db_db_message_proto_msgTypes,
	}.Build()
	File_protos_amass_db_db_message_proto = out.File
	file_protos_amass_db_db_message_proto_rawDesc = nil
	file_protos_amass_db_db_message_proto_goTypes = nil
	file_protos_amass_db_db_message_proto_depIdxs = nil
}
